version: '2'
services:
  ovpn:
    image: tkaefer/openvpn-client-container
    cap_add:
      - NET_ADMIN # needed to be set for being able to setup tun device in container
    volumes:
      - ./client.ovpn:/etc/openvpn/client.conf # be aware of client and server settings about `redirect-gateway`
      - ./dropbear:/etc/dropbear # Good to have persistent host keys, but not really required
    environment:
      - USER_KEY="ssh-rsa ... user@host"
